name: Erlang CI com OpenSUSE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar Erlang e Rebar3
      run: |
        zypper refresh
        zypper install -y erlang rebar3
        erl -version
        rebar3 --version
      shell: bash

    - name: Compilar projeto
      run: rebar3 compile
      shell: bash

    - name: Rodar testes
      run: rebar3 do eunit, ct
      shell: bash
