name: Erlang CI com OpenSUSE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar dependências do sistema e Erlang
      run: |
        zypper refresh
        # Instalar SOMENTE Erlang e outras ferramentas necessárias como git e wget
        # REBAR3 FOI REMOVIDO DESTA LINHA
        zypper install -y erlang git wget
        erl -version
      shell: bash

    - name: Instalar Rebar3
      run: |
        # Busca a versão 3.25.0 do rebar3 (ou a mais recente)
        wget https://github.com/erlang/rebar3/releases/download/3.25.0/rebar3
        chmod +x rebar3
        ./rebar3 local install # Instala o rebar3 em ~/.cache/rebar3/bin
        echo "$HOME/.cache/rebar3/bin" >> $GITHUB_PATH # Adiciona o rebar3 ao PATH
        rebar3 --version
      shell: bash

    - name: Compilar projeto
      run: rebar3 compile
      shell: bash

    - name: Rodar testes
      run: rebar3 do eunit, ct
      shell: bash