name: Erlang CI Definitivo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Instalar dependências (Erlang, Bash e Curl)
      id: setup_erlang
      run: |
        zypper --non-interactive refresh
        zypper --non-interactive install -y erlang git bash which curl
        echo "ERLANG_OTP_RELEASE=$(erl -noshell -eval 'erlang:display(erlang:system_info(otp_release)), halt().' | tr -d '"')" >> $GITHUB_OUTPUT
        echo "Versão do Erlang/OTP instalada: $(erl -version)"
      shell: sh

    - name: 3. Instalar Rebar3 (Versão Correta 3.25.0)
      id: install_rebar3
      run: |
        # Usando a versão estável mais recente confirmada: 3.25.0
        REBAR3_VERSION="3.25.0"
        echo "Instalando Rebar3 v${REBAR3_VERSION}..."

        REBAR3_BIN_DIR="$HOME/.local/bin"
        mkdir -p "$REBAR3_BIN_DIR"

        echo "Baixando rebar3..."
        curl -fLso "${REBAR3_BIN_DIR}/rebar3" "https://github.com/erlang/rebar3/releases/download/${REBAR3_VERSION}/rebar3"
        
        chmod +x "${REBAR3_BIN_DIR}/rebar3"

        echo "${REBAR3_BIN_DIR}" >> $GITHUB_PATH
        export PATH="${REBAR3_BIN_DIR}:$PATH"

        echo "Rebar3 instalado com sucesso em: $(which rebar3)"
        rebar3 --version
      # A partir daqui, usamos o caminho absoluto para o bash para evitar erros de PATH.
      shell: /usr/bin/bash

    - name: 4. Configurar Cache (Passo Crítico para Estabilidade)
      id: cache
      uses: actions/cache@v4
      with:
        # Cachear o PLT do Dialyzer (em ~/.cache/rebar3) e os artefatos de build (_build)
        # é a solução mais eficaz para evitar erros de Dialyzer em ambientes de CI.
        path: |
          ~/.cache/rebar3
          _build
        key: ci-cache-${{ runner.os }}-${{ steps.setup_erlang.outputs.ERLANG_OTP_RELEASE }}-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ci-cache-${{ runner.os }}-${{ steps.setup_erlang.outputs.ERLANG_OTP_RELEASE }}-

    - name: 5. Compilar Projeto
      id: compile
      run: |
        rebar3 compile
      shell: /usr/bin/bash

    - name: 6. Rodar Análise Estática (Xref)
      id: xref
      run: |
        rebar3 xref
      shell: /usr/bin/bash

    - name: 7. Rodar Análise de Tipos (Dialyzer)
      id: dialyzer
      run: |
        rebar3 dialyzer
      shell: /usr/bin/bash

    - name: 8. Rodar Testes
      id: tests
      run: |
        rebar3 do eunit, ct
      shell: /usr/bin/bash

    - name: 9. Upload de Crashdump (em caso de falha)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: rebar3-crashdump-${{ runner.os }}-${{ steps.setup_erlang.outputs.ERLANG_OTP_RELEASE }}
        path: |
          rebar3.crashdump
          ./rebar3.crashdump
          _build/default/rebar3.crashdump
          _build/test/rebar3.crashdump
        if-no-files-found: warn