name: Erlang CI com OpenSUSE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar dependências do sistema e Erlang
      run: |
        zypper refresh
        # Install Erlang and other necessary tools like git and wget
        zypper install -y erlang git wget
        erl -version
      shell: bash

    - name: Instalar Rebar3
      run: |
        wget https://github.com/erlang/rebar3/releases/download/3.22.1/rebar3 # Fetches a specific version, check for the latest
        chmod +x rebar3
        ./rebar3 local install # Installs rebar3 to ~/.cache/rebar3/bin
        echo "$HOME/.cache/rebar3/bin" >> $GITHUB_PATH # Adds rebar3 to PATH
        rebar3 --version
      shell: bash

    - name: Compilar projeto
      run: rebar3 compile
      shell: bash

    - name: Rodar testes
      run: rebar3 do eunit, ct
      shell: bash