name: Erlang CI Definitivo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Instalar dependências e Definir Paths
      id: setup_erlang
      run: |
        zypper --non-interactive refresh
        zypper --non-interactive install -y erlang git bash which curl coreutils
        
        # Descobre o diretório de binários do Erlang
        ERLANG_BIN_DIR="$(erl -noshell -eval 'io:format("~s/bin", [code:root_dir()]), halt().')"
        echo "Diretório de binários do Erlang: ${ERLANG_BIN_DIR}"
        
        # Adiciona ao GITHUB_PATH para os passos futuros
        echo "${ERLANG_BIN_DIR}" >> $GITHUB_PATH
        
        # --- A CORREÇÃO CRÍTICA ---
        # Define o caminho como um 'output' para ser usado no próximo passo
        echo "erlang_bin_dir=${ERLANG_BIN_DIR}" >> $GITHUB_OUTPUT
        
        echo "ERLANG_OTP_RELEASE=$(erl -noshell -eval 'erlang:display(erlang:system_info(otp_release)), halt().' | tr -d '"')" >> $GITHUB_OUTPUT
      shell: sh

    - name: 3. Instalar Rebar3
      id: install_rebar3
      run: |
        # Recebemos o caminho do Erlang do passo anterior
        ERLANG_BIN_DIR_FROM_STEP2="${{ steps.setup_erlang.outputs.erlang_bin_dir }}"
        
        REBAR3_VERSION="3.25.0"
        echo "Instalando Rebar3 v${REBAR3_VERSION}..."

        REBAR3_BIN_DIR="$HOME/.local/bin"
        mkdir -p "$REBAR3_BIN_DIR"

        echo "Baixando rebar3..."
        curl -fLso "${REBAR3_BIN_DIR}/rebar3" "https://github.com/erlang/rebar3/releases/download/${REBAR3_VERSION}/rebar3"
        chmod +x "${REBAR3_BIN_DIR}/rebar3"

        # Adiciona o diretório do Rebar3 ao GITHUB_PATH
        echo "${REBAR3_BIN_DIR}" >> $GITHUB_PATH
        
        # Constrói o PATH para a sessão atual usando o valor do output
        export PATH="${ERLANG_BIN_DIR_FROM_STEP2}:${REBAR3_BIN_DIR}:$PATH"

        echo "PATH da sessão atual: $PATH"
        echo "Rebar3 instalado em: $(which rebar3)"
        rebar3 --version
      shell: /usr/bin/bash {0}

    - name: 4. Configurar Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/rebar3
          _build
        key: ci-cache-${{ runner.os }}-${{ steps.setup_erlang.outputs.ERLANG_OTP_RELEASE }}-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ci-cache-${{ runner.os }}-${{ steps.setup_erlang.outputs.ERLANG_OTP_RELEASE }}-

    - name: 5. Compilar Projeto
      id: compile
      run: |
        rebar3 compile
      shell: /usr/bin/bash {0}

    - name: 6. Rodar Análise Estática (Xref)
      id: xref
      run: |
        rebar3 xref
      shell: /usr/bin/bash {0}

    - name: 7. Rodar Análise de Tipos (Dialyzer)
      id: dialyzer
      run: |
        rebar3 dialyzer
      shell: /usr/bin/bash {0}

    - name: 8. Rodar Testes
      id: tests
      run: |
        rebar3 do eunit, ct
      shell: /usr/bin/bash {0}

    - name: 9. Upload de Crashdump (em caso de falha)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: rebar3-crashdump-${{ runner.os }}-${{ steps.setup_erlang.outputs.ERLANG_OTP_RELEASE }}
        path: |
          rebar3.crashdump
          ./rebar3.crashdump
          _build/default/rebar3.crashdump
          _build/test/rebar3.crashdump
        if-no-files-found: warn