name: Erlang CI (com Setup Unificado)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Instalar Erlang e Rebar3 (Setup Unificado)
      id: setup
      run: |
        echo "Instalando dependências do sistema..."
        zypper --non-interactive refresh
        zypper --non-interactive install -y erlang git curl which coreutils

        echo "Configurando PATH do Erlang..."
        ERLANG_BIN_DIR="$(erl -noshell -eval 'io:format("~s/bin", [code:root_dir()]), halt().')"

        echo "Instalando Rebar3..."
        REBAR3_VERSION="3.25.0"
        REBAR3_BIN_DIR="$HOME/.local/bin"
        mkdir -p "$REBAR3_BIN_DIR"
        curl -fLso "${REBAR3_BIN_DIR}/rebar3" "https://github.com/erlang/rebar3/releases/download/${REBAR3_VERSION}/rebar3"
        chmod +x "${REBAR3_BIN_DIR}/rebar3"

        echo "Exportando paths..."
        echo "${ERLANG_BIN_DIR}" >> $GITHUB_PATH
        echo "${REBAR3_BIN_DIR}" >> $GITHUB_PATH

        export PATH="${ERLANG_BIN_DIR}:${REBAR3_BIN_DIR}:$PATH"
        echo "--- Verificação ---"
        echo "PATH: $PATH"
        echo -n "Versão do Erlang: "; erl -version
        echo -n "Versão do Rebar3: "; rebar3 --version
        echo "-------------------"

        echo "ERLANG_OTP_RELEASE=$(erl -noshell -eval 'erlang:display(erlang:system_info(otp_release)), halt().' | tr -d '"')" >> $GITHUB_OUTPUT
      

    - name: 3. Configurar Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/rebar3
          _build
        key: ci-cache-${{ runner.os }}-${{ steps.setup.outputs.ERLANG_OTP_RELEASE }}-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ci-cache-${{ runner.os }}-${{ steps.setup.outputs.ERLANG_OTP_RELEASE }}-

    - name: 4. Compilar Projeto
      run: rebar3 compile

    - name: 5. Rodar Análise Estática (Xref)
      run: rebar3 xref

    - name: 6. Rodar Análise de Tipos (Dialyzer)
      run: rebar3 dialyzer

    - name: 7. Rodar Testes
      run: rebar3 do eunit, ct

    - name: 8. Upload de Crashdump (em caso de falha)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: rebar3-crashdump-${{ runner.os }}-${{ steps.setup.outputs.ERLANG_OTP_RELEASE }}
        path: |
          rebar3.crashdump
          ./rebar3.crashdump
          _build/default/rebar3.crashdump
          _build/test/rebar3.crashdump
        if-no-files-found: warn
