name: Erlang CI com OpenSUSE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar dependências do sistema e Erlang
      run: |
        zypper refresh
        zypper install -y erlang git wget
        erl -version
      shell: bash

    - name: Instalar Rebar3
      run: |
        wget https://github.com/erlang/rebar3/releases/download/3.25.0/rebar3
        chmod +x rebar3
        ./rebar3 local install # Instala o rebar3 em ~/.cache/rebar3/bin

        REBAR3_BIN_DIR="$HOME/.cache/rebar3/bin"
        # Define REBAR3_BIN_DIR como uma variável de ambiente para os próximos passos
        echo "REBAR3_BIN_DIR=${REBAR3_BIN_DIR}" >> $GITHUB_ENV

        # Exporta o PATH para uso no rebar3 --version deste passo
        export PATH="${REBAR3_BIN_DIR}:$PATH"

        echo "Rebar3 bin directory: ${REBAR3_BIN_DIR}"
        echo "PATH neste passo (Instalar Rebar3): $PATH"
        rebar3 --version
      shell: bash

    - name: Compilar projeto
      run: |
        # Adiciona o diretório do rebar3 ao PATH no início deste passo
        export PATH="${REBAR3_BIN_DIR}:$PATH"
        echo "PATH atualizado no passo 'Compilar projeto': $PATH"
        rebar3 compile
      shell: bash

    - name: Rodar testes
      id: run_tests # Adiciona um ID para referenciar o resultado do passo
      run: |
        # Adiciona o diretório do rebar3 ao PATH no início deste passo
        export PATH="${REBAR3_BIN_DIR}:$PATH"
        echo "PATH atualizado no passo 'Rodar testes': $PATH"
        # Executa os testes com DIAGNOSTIC=1 para obter mais informações em caso de erro
        DIAGNOSTIC=1 rebar3 do eunit, ct
      shell: bash

    - name: Upload rebar3 crashdump (se houver falha nos testes)
      # Este passo só será executado se o passo 'Rodar testes' falhar
      if: steps.run_tests.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: rebar3-crashdump
        # O rebar3.crashdump geralmente é criado no diretório raiz do projeto
        # ou no diretório _build. Verifique a saída do rebar3 se não encontrar.
        path: |
          rebar3.crashdump
          _build/default/rebar3.crashdump
          _build/test/rebar3.crashdump 
        if-no-files-found: ignore # Não falhar o workflow se o arquivo não for encontrado